"""
project_creator.py — Project Creator Agent for GitHub Activity Automation System.

Creates a new stub GitHub repository on a configurable schedule, seeding it
with language-appropriate starter files.  Optionally uses the HuggingFace
Inference API to generate project ideas; falls back to a built-in list.

Usage:
    python project_creator.py              # Normal run (respects interval)
    python project_creator.py --force      # Bypass interval check
    python project_creator.py --lang js    # Force JavaScript project
"""

import argparse
import random
import re
import sys
from datetime import datetime, timedelta

import requests
from dotenv import load_dotenv

from github_client import GitHubClient, GitHubError
from utils import (
    get_github_token,
    is_kill_switch_active,
    load_config,
    load_state,
    save_state,
    setup_logger,
    today_str,
)

load_dotenv()


# ── Starter file templates ────────────────────────────────────────────────────

PYTHON_MAIN = """\
\"\"\"
{project_name} — {description}

Generated by GitHub Activity Automation System.
\"\"\"


def main() -> None:
    print("Hello from {project_name}!")


if __name__ == "__main__":
    main()
"""

PYTHON_GITIGNORE = """\
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.env
venv/
.venv/
*.log
"""

JS_INDEX = """\
/**
 * {project_name} — {description}
 *
 * Generated by GitHub Activity Automation System.
 */

function main() {{
  console.log("Hello from {project_name}!");
}}

main();
"""

JS_GITIGNORE = """\
node_modules/
dist/
.env
*.log
npm-debug.log*
"""

JS_PACKAGE_JSON = """\
{{
  "name": "{project_name}",
  "version": "1.0.0",
  "description": "{description}",
  "main": "index.js",
  "scripts": {{
    "start": "node index.js"
  }},
  "keywords": [],
  "author": "",
  "license": "MIT"
}}
"""

README_TEMPLATE = """\
# {project_name}

{description}

## Getting Started

### Prerequisites

{prerequisites}

### Installation

```bash
git clone https://github.com/{owner}/{repo_name}.git
cd {repo_name}
{install_cmd}
```

### Usage

```bash
{run_cmd}
```

## Project Structure

```
{repo_name}/
{structure}
```

---
*Auto-generated stub project.*
"""


def build_readme(
    project_name: str,
    description: str,
    owner: str,
    repo_name: str,
    language: str,
) -> str:
    if language == "python":
        prerequisites = "- Python 3.10+"
        install_cmd = "# No extra dependencies for this stub"
        run_cmd = "python main.py"
        structure = "├── main.py\n├── .gitignore\n└── README.md"
    else:
        prerequisites = "- Node.js 18+"
        install_cmd = "npm install"
        run_cmd = "npm start"
        structure = "├── index.js\n├── package.json\n├── .gitignore\n└── README.md"

    return README_TEMPLATE.format(
        project_name=project_name,
        description=description,
        owner=owner,
        repo_name=repo_name,
        prerequisites=prerequisites,
        install_cmd=install_cmd,
        run_cmd=run_cmd,
        structure=structure,
    )


# ── AI idea generation ────────────────────────────────────────────────────────

def fetch_ai_project_idea(logger) -> str | None:
    """
    Try to generate a short project idea using the HuggingFace Inference API.
    Returns a string on success, None on any failure (caller falls back to
    the built-in list — never crashes).
    """
    import os

    hf_token = os.environ.get("HUGGINGFACE_TOKEN", "").strip()
    if not hf_token:
        logger.info("HUGGINGFACE_TOKEN not set — skipping AI idea generation.")
        return None

    url = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1"
    prompt = (
        "Generate a single short (under 10 words) unique open-source project idea "
        "suitable for a beginner programmer. Reply with ONLY the idea, no explanation."
    )
    payload = {
        "inputs": f"<s>[INST] {prompt} [/INST]",
        "parameters": {"max_new_tokens": 40, "temperature": 0.9},
    }
    headers = {"Authorization": f"Bearer {hf_token}"}

    try:
        resp = requests.post(url, json=payload, headers=headers, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        if isinstance(data, list) and data:
            raw = data[0].get("generated_text", "")
            # Strip the prompt echo (HuggingFace echoes the input)
            idea = raw.replace(prompt, "").strip().strip('"').strip("'")
            # Keep only the first sentence / short phrase
            idea = re.split(r"[.\n]", idea)[0].strip()
            if 3 < len(idea) < 80:
                logger.info("AI-generated project idea: '%s'.", idea)
                return idea
    except Exception as exc:  # noqa: BLE001
        logger.warning("AI API call failed (%s) — falling back to built-in list.", exc)

    return None


def slugify(name: str) -> str:
    """Convert a project name to a GitHub-safe repo slug."""
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug).strip("-")
    return slug or "my-project"


# ── Helpers ───────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Project Creator Agent — periodically creates stub GitHub repos."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Bypass the interval check and create a project now.",
    )
    parser.add_argument(
        "--lang",
        choices=["python", "javascript", "js"],
        default=None,
        help="Override the language for this run.",
    )
    return parser.parse_args()


def is_interval_elapsed(state: dict, interval_days: int) -> bool:
    """Return True if enough days have passed since the last project was created."""
    last_run = state.get("last_run_date", "")
    if not last_run:
        return True
    try:
        last_dt = datetime.strptime(last_run, "%Y-%m-%d")
    except ValueError:
        return True
    return datetime.utcnow() >= last_dt + timedelta(days=interval_days)


def pick_project_name(config: dict, state: dict, logger) -> tuple[str, str]:
    """
    Return (raw_idea, repo_slug).  Tries AI API first, falls back to
    built-in list and avoids previously created projects.
    """
    created: list[str] = state.get("created_projects", [])
    pc_cfg = config["project_creator"]
    builtin_ideas: list[str] = pc_cfg.get("project_ideas", [])

    use_ai = pc_cfg.get("use_ai_api", False)
    idea: str | None = None

    if use_ai:
        idea = fetch_ai_project_idea(logger)

    if not idea:
        # Filter out already-created projects
        remaining = [i for i in builtin_ideas if slugify(i) not in created]
        if not remaining:
            remaining = builtin_ideas  # All used — allow repeats
            logger.warning("All built-in ideas have been used; cycling back.")
        idea = random.choice(remaining)

    slug = slugify(idea)
    # Ensure uniqueness by appending a date suffix when needed
    if slug in created:
        slug = f"{slug}-{today_str()}"

    return idea, slug


def seed_files(
    client: GitHubClient,
    owner: str,
    repo_name: str,
    project_name: str,
    description: str,
    language: str,
    branch: str,
    logger,
) -> None:
    """Push all starter files to the freshly created repository."""
    readme_content = build_readme(project_name, description, owner, repo_name, language)

    files: list[tuple[str, str]] = [
        ("README.md", readme_content),
    ]

    if language == "python":
        files.append(("main.py", PYTHON_MAIN.format(
            project_name=project_name, description=description
        )))
        files.append((".gitignore", PYTHON_GITIGNORE))
    else:  # javascript
        files.append(("index.js", JS_INDEX.format(
            project_name=project_name, description=description
        )))
        files.append((".gitignore", JS_GITIGNORE))
        files.append(("package.json", JS_PACKAGE_JSON.format(
            project_name=project_name, description=description
        )))

    for file_path, content in files:
        try:
            client.create_or_update_file(
                owner=owner,
                repo=repo_name,
                path=file_path,
                message=f"chore: add {file_path} [automated]",
                content=content,
                branch=branch,
            )
            logger.info("  ✓ Created '%s' in '%s'.", file_path, repo_name)
        except GitHubError as exc:
            logger.error("  ✗ Failed to create '%s': %s", file_path, exc)
            raise


# ── Main ──────────────────────────────────────────────────────────────────────

def run_project_creator(force: bool = False, lang_override: str | None = None) -> None:
    config = load_config()
    logger = setup_logger("project_creator", config)

    logger.info("Project Creator Agent starting.")

    # ── Kill switch ───────────────────────────────────────────────────────────
    if is_kill_switch_active(config, logger):
        sys.exit(0)

    pc_cfg = config["project_creator"]
    state = load_state(pc_cfg["state_file"])
    interval_days = int(pc_cfg.get("run_interval_days", 3))

    # ── Interval check ────────────────────────────────────────────────────────
    if not force and not is_interval_elapsed(state, interval_days):
        last_run = state.get("last_run_date", "unknown")
        logger.info(
            "Project Creator last ran on %s (interval: %d days). "
            "Use --force to run now.",
            last_run,
            interval_days,
        )
        return

    # ── Auth ──────────────────────────────────────────────────────────────────
    try:
        token = get_github_token()
    except EnvironmentError as exc:
        logger.error("Missing GitHub token: %s", exc)
        sys.exit(1)

    client = GitHubClient(token)

    try:
        user = client.get_authenticated_user()
        owner = user["login"]
        logger.info("Authenticated as '%s'.", owner)
    except GitHubError as exc:
        logger.error("Authentication failed: %s", exc)
        sys.exit(1)

    # ── Pick project ──────────────────────────────────────────────────────────
    raw_idea, repo_slug = pick_project_name(config, state, logger)
    project_name = repo_slug.replace("-", " ").title()
    description = raw_idea

    # ── Choose language ───────────────────────────────────────────────────────
    if lang_override:
        language = "javascript" if lang_override == "js" else lang_override
    else:
        supported = pc_cfg.get("supported_languages", ["python", "javascript"])
        language = random.choice(supported)

    logger.info(
        "Creating project '%s' (slug: '%s', language: %s).",
        project_name,
        repo_slug,
        language,
    )

    # ── Create repo ───────────────────────────────────────────────────────────
    private = pc_cfg.get("repo_visibility", "public") != "public"
    try:
        repo = client.create_repo(
            name=repo_slug,
            description=description,
            private=private,
        )
        logger.info("Repository '%s' created at %s.", repo_slug, repo["html_url"])
    except GitHubError as exc:
        logger.error("Failed to create repository '%s': %s", repo_slug, exc)
        sys.exit(1)

    # ── Seed initial commit (README) to create default branch ────────────────
    # GitHub doesn't create a branch until the first file is pushed.
    branch = "main"
    try:
        client.create_or_update_file(
            owner=owner,
            repo=repo_slug,
            path="README.md",
            message="chore: initial commit [automated]",
            content=build_readme(project_name, description, owner, repo_slug, language),
            branch=branch,
        )
    except GitHubError as exc:
        logger.error("Failed to seed initial README: %s", exc)
        sys.exit(1)

    # ── Seed remaining files ──────────────────────────────────────────────────
    remaining_files: list[tuple[str, str]] = []
    if language == "python":
        remaining_files = [
            ("main.py", PYTHON_MAIN.format(
                project_name=project_name, description=description
            )),
            (".gitignore", PYTHON_GITIGNORE),
        ]
    else:
        remaining_files = [
            ("index.js", JS_INDEX.format(
                project_name=project_name, description=description
            )),
            (".gitignore", JS_GITIGNORE),
            ("package.json", JS_PACKAGE_JSON.format(
                project_name=project_name, description=description
            )),
        ]

    for file_path, content in remaining_files:
        try:
            client.create_or_update_file(
                owner=owner,
                repo=repo_slug,
                path=file_path,
                message=f"chore: add {file_path} [automated]",
                content=content,
                branch=branch,
            )
            logger.info("  ✓ Created '%s'.", file_path)
        except GitHubError as exc:
            logger.error("  ✗ Failed to create '%s': %s", file_path, exc)

    # ── Persist state ─────────────────────────────────────────────────────────
    created = state.get("created_projects", [])
    created.append(repo_slug)
    state.update(
        {
            "last_run_date": today_str(),
            "last_project": repo_slug,
            "created_projects": created,
        }
    )
    save_state(pc_cfg["state_file"], state)
    logger.info(
        "Project Creator Agent finished. Repository '%s' is live at %s.",
        repo_slug,
        repo.get("html_url", ""),
    )


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    args = parse_args()
    run_project_creator(force=args.force, lang_override=args.lang)
